### ISSUE TITLE
env Parameters [url, key]

### ISSUE THREAD

**Issue by keepjhonnying** [guilhermebkel/NETCLAROWIFI-Autoconnect#7]
Hi

Whats the parameters  url and key in env file?
Any value i put in URL show this message when run:

`  message: 'Protocol error (Page.navigate): Invalid parameters url: string value expected' }`

Tried
https://www61.netcombowifi.com.br/portal/netwifi/sponsored.htm
https://www61.netcombowifi.com.br/portal/netwifi/greetings.htm
https://www61.netcombowifi.com.br/portal/netwifi/index.htm
google.com
google

all with quotes and without

P.S VERY GREAT APP

**Comment by guilhermebkel** [comment]
## Hello! Thanks for the fork!

#### Try to use the .env the way below, without the EMAIL, PASSWORD and URL (Because I didn't finished the script with login method)
#### In the KEY field, you'll have to make the following process to get your key url
- Connect to the wifi using your celphone
- It probably will show a message on the notifications asking you for logging in, so, click on this message
- You'll go to the login page (if you're redirected to this by the native browser on your celphone, try to change it to the google chrome browser or any other that you can access the browser url field)
- Make the login using your credentials. After doing that, you'll notice that the url will get bigger (because now it is going to be the page url + your token)
- This big url is the one you'll need to paste on the KEY field of .env file
```
EMAIL=
PASSWORD=
URL=
KEY=your_url_with_key
AUTOCONNECT=true
TIME_INTERVAL=1
```

**Comment by keepjhonnying** [comment]
it Works.

i can get the url the Lynx too.


Tkz

**Comment by keepjhonnying** [comment]
Tip:

To get the URL [key param] on the Desktop:

Previous logged on the #NET-CLARO-WIFI, but without connecttion
Open the browser [Chorme, opera, etc]
Open a new tab [Ctrl+T]
Open DevTools [Ctrl+Shift+i]
On DevTools click on tab NetWork
Click on Recording
Check Preserve log
![Screenshot_2019-08-04_12-28-56](https://user-images.githubusercontent.com/5790653/62426486-83507480-b6b3-11e9-9360-b43f3731cb65.png)

Enter 8.8.8.8 on Address bar, hit Enter
You will be directed  to Connect page
On DevTools, look for index.html?key=xxxxx...
![Screenshot_2019-08-04_12-33-54](https://user-images.githubusercontent.com/5790653/62426551-24d7c600-b6b4-11e9-9f4d-213b1739da91.png)

Copy the url!

**Comment by guilhermebkel** [comment]
Thnks! I'll add it to the README.md with the necessary credits ^^
